version: '3'
services:
  db:
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "root"
    ports:
      - "3309:3309"
    volumes:
      - db-store:/var/lib/mysql

  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./src/public:/work/backend
    depends_on:
      - app

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db

volumes:
  db-store:
